/**
 * Builds the world basemap the Program map draws on.
 *
 * Reads Natural Earth 1:110m admin-0 countries and writes a reduced outline
 * set to `src/app/program/[programId]/world-110m.json`. Committed as an asset
 * and regenerated by hand, never at build time: a map that silently redraws
 * itself because an upstream file moved is a map nobody can review a diff of.
 *
 *     pnpm basemap:build
 *
 * **Why a bundled outline rather than map tiles.** Tiles would mean a network
 * call per view from an app that otherwise refuses to boot rather than degrade
 * — a blank grey square where the map was is exactly the silent failure this
 * codebase spends its comments avoiding. Outlines ship with the app, render on
 * the server, and cost nothing at request time.
 *
 * **Three reductions, and what each is worth.** 819 KB in, ~104 KB out:
 *
 * - `RDP_EPSILON_DEG` collapses points that sit within 0.1° of the line they
 *   span. Europe is the tightest camera at 44° across roughly 400 px, so 0.1°
 *   is about one pixel there and invisible in every other view.
 * - `COORDINATE_DECIMALS` of 2 is ~1.1 km at the equator. The map plots city
 *   centroids that are themselves ±5 km, so a third decimal would be a
 *   precision the underlying points do not have.
 * - `MIN_RING_AREA_SQ_DEG` drops islands below 0.5 square degrees, which at
 *   world zoom are smaller than the supplier dots drawn over them.
 *
 * Country identity is kept as ISO3 even though the current map only draws
 * outlines: it is two bytes a country, and without it a later choropleth would
 * have to rebuild the asset to get the join key back.
 */

import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const SOURCE_URL =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson';

const OUTPUT_PATH = resolve(
  import.meta.dirname,
  '../src/app/program/[programId]/world-110m.json',
);

const RDP_EPSILON_DEG = 0.1;
const COORDINATE_DECIMALS = 2;
const MIN_RING_AREA_SQ_DEG = 0.5;

/** A closed ring, flattened to `[lon, lat, lon, lat, …]` to halve the JSON. */
type FlatRing = number[];
type Country = { id: string; r: FlatRing[] };

type Position = [number, number];
type Geometry =
  | { type: 'Polygon'; coordinates: Position[][] }
  | { type: 'MultiPolygon'; coordinates: Position[][][] }
  | { type: string; coordinates: unknown };

type Feature = { properties: Record<string, string | number | null>; geometry: Geometry };

function ringsOf(geometry: Geometry): Position[][] {
  if (geometry.type === 'Polygon') return geometry.coordinates as Position[][];
  if (geometry.type === 'MultiPolygon') {
    return (geometry.coordinates as Position[][][]).flat();
  }
  return [];
}

/** Shoelace area in square degrees — a size filter, not a real-world area. */
function ringArea(ring: Position[]): number {
  let sum = 0;
  for (let i = 0; i < ring.length - 1; i += 1) {
    const a = ring[i]!;
    const b = ring[i + 1]!;
    sum += a[0] * b[1] - b[0] * a[1];
  }
  return Math.abs(sum) / 2;
}

/**
 * Ramer–Douglas–Peucker, iterative rather than recursive: Antarctica's ring
 * is deep enough to blow a recursive implementation's stack on some inputs,
 * and an explicit stack costs nothing to read.
 */
function simplify(points: Position[], epsilon: number): Position[] {
  if (points.length < 3) return points;
  const keep = new Uint8Array(points.length);
  keep[0] = 1;
  keep[points.length - 1] = 1;
  const stack: Array<[number, number]> = [[0, points.length - 1]];

  while (stack.length > 0) {
    const [first, last] = stack.pop()!;
    if (last <= first + 1) continue;
    const a = points[first]!;
    const b = points[last]!;
    const dx = b[0] - a[0];
    const dy = b[1] - a[1];
    const span = Math.hypot(dx, dy);

    let worst = 0;
    let worstAt = first;
    for (let i = first + 1; i < last; i += 1) {
      const p = points[i]!;
      const distance =
        span === 0
          ? Math.hypot(p[0] - a[0], p[1] - a[1])
          : Math.abs(dy * p[0] - dx * p[1] + b[0] * a[1] - b[1] * a[0]) / span;
      if (distance > worst) {
        worst = distance;
        worstAt = i;
      }
    }

    if (worst > epsilon) {
      keep[worstAt] = 1;
      stack.push([first, worstAt], [worstAt, last]);
    }
  }

  return points.filter((_, i) => keep[i] === 1);
}

async function main(): Promise<void> {
  process.stdout.write(`reading ${SOURCE_URL}\n`);
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Natural Earth returned ${response.status} ${response.statusText}`);
  }
  const collection = (await response.json()) as { features: Feature[] };

  const countries: Country[] = [];
  let pointsIn = 0;
  let pointsOut = 0;

  for (const feature of collection.features) {
    const properties = feature.properties;
    // ISO_A3 is the literal string "-99" for the disputed and the stateless.
    // ISO_A3_EH carries a usable code for most of them; ADM0_ISO is the last
    // resort, and a country that has none is still drawn, just unlabelled.
    const raw = [properties.ISO_A3, properties.ISO_A3_EH, properties.ADM0_ISO];
    const id = raw.find((v): v is string => typeof v === 'string' && v !== '-99') ?? '';

    const rings: FlatRing[] = [];
    for (const ring of ringsOf(feature.geometry)) {
      pointsIn += ring.length;
      if (ringArea(ring) < MIN_RING_AREA_SQ_DEG) continue;

      const flat: FlatRing = [];
      let previousLon: number | undefined;
      let previousLat: number | undefined;
      for (const [lon, lat] of simplify(ring, RDP_EPSILON_DEG)) {
        const roundedLon = Number(lon.toFixed(COORDINATE_DECIMALS));
        const roundedLat = Number(lat.toFixed(COORDINATE_DECIMALS));
        // Rounding can fold neighbouring points onto each other; a repeated
        // point is a wasted pair of numbers in every view that draws it.
        if (roundedLon === previousLon && roundedLat === previousLat) continue;
        flat.push(roundedLon, roundedLat);
        previousLon = roundedLon;
        previousLat = roundedLat;
      }

      // Fewer than four points is not a polygon any camera would show.
      if (flat.length >= 8) {
        rings.push(flat);
        pointsOut += flat.length / 2;
      }
    }

    if (rings.length > 0) countries.push({ id, r: rings });
  }

  const json = JSON.stringify(countries);
  await writeFile(OUTPUT_PATH, `${json}\n`, 'utf8');

  process.stdout.write(
    `${countries.length} countries · ${pointsIn} points in, ${pointsOut} out · ` +
      `${(json.length / 1024).toFixed(0)} KB\n`,
  );
  process.stdout.write(`wrote ${OUTPUT_PATH}\n`);
}

await main();
